const puppeteer = require('puppeteer');


(async () => {

    const args = [
        '--disable-infobars',
        '--install-autogenerated-theme=94,53,177',
        '--omnibox-ui-hide-steady-state-url-scheme',
        '--omnibox-ui-hide-steady-state-url-trivial-subdomains',
        '--disable-blink-features=AutomationControlled',
        '--dont-require-litepage-redirect-infobar',
    ]

    const ignoreDefaultArgs = [
        '--disable-blink-features=AutomationControlled',
        '--enable-automation',
        '--disable-extensions',
        '--disable-extensions-except',
        '--disable-extensions-file-access-check',
        '--disable-extensions-http-throttling',
        'about:blank',
        '--about:blank',
    ]

    const browser = await puppeteer.launch({headless: false, args: args, ignoreDefaultArgs: ignoreDefaultArgs})
    

    //console.log(puppeteer.defaultArgs())
    const browser_pages = await browser.pages()
    const page = await browser.newPage()
    
    await page.setViewport({
        width: 1920,
        height: 1080,
        deviceScaleFactor: 1,
    });
    await page.setGeolocation({latitude: 59.95, longitude: 30.31667});
    
    //await browser_pages[0].close()

    browser.on('targetcreated', async (target) => {
        //let page = await browser.newPage()
        //page = await new_page.page();
        if(target.type() === 'page'){
            console.log('Browser opened new tab');
            const page = await target.page();
            await page.evaluateOnNewDocument(()=>{
                Object.defineProperty(navigator.__proto__, 'deviceMemory', {
                    value: '99999999999'
                })
        
                Object.defineProperty(navigator.__proto__, 'hardwareConcurrency', {
                    value: '9'
                })
        
                Object.defineProperty(navigator.__proto__, 'platform', {
                    value: 'Hacked'
                })
    
                Object.defineProperty(navigator.__proto__, 'vendor', {
                    value: 'Hacked'
                })
    
                Object.defineProperty(navigator.__proto__, 'appVersion', {
                    value: 'Hacked'
                })
        
            })
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36');
        }
        
    });

    

    /*await puppeteer.createBrowserFetcher({
        plateform: 'mac'
    })
    console.log(process.env)*/
    
})();